### ISSUE TITLE
Final Capstone Group Project composition

### ISSUE THREAD

**Issue by rtonata88** [rtonata88/car-rental#12]
We are a group of the following 3 members:

- @oliverSCZ 
- @danalvrz 
- @rtonata88 

Kanban board project link: https://github.com/rtonata88/car-rental/projects/1

![Screen Shot 2022-05-23 at 7 29 43 PM](https://user-images.githubusercontent.com/18032597/169875222-97c8fc5a-6eb6-4372-9f39-f422a490c058.png)

**Comment by MuriloRoque** [comment]
Hi @rtonata88, @oliverSCZ, @danalvrz,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
